version: '3'
services:
  unionpolygon_postgres:
    container_name: unionpolygon_postgres
    build: ./docker/postgres
    volumes:
      - unionpolygon_pgdata:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin
    ports:
      - 5431:5432
  unionpolygon_app:
    container_name: unionpolygon_app
    volumes:
      - .:/app
    restart: always
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./.env
    working_dir: '/app'
    depends_on:
      - unionpolygon_postgres
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8001:8000
volumes:
  unionpolygon_pgdata:
    driver: local
