# Generated by Django 3.1.6 on 2021-02-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('farmlands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmland',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
    ]
