# Generated by Django 3.1.6 on 2021-02-08 08:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prefectures', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefectures.prefecture')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('prefecture', 'name'), name='unique_city'),
        ),
    ]
